env: local
appName: k-style-test
salt: "1234"
jwtSecret: "abcdefghijklmnop"
appUrl: http://localhost:3000
port: 3000
dbUsername: root
dbPassword:
dbPort: 3306
dbHost: 127.0.0.1
dbName: kstylehub
log:
  filenamePrefix: log/kstylehub